project/axf/urls.py
from django.conf.urls import url,include

from . import views

urlpatterns = [
    url(r'^home/$', views.home,name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market,name='market'),
    url(r'^cart/$', views.cart,name='cart'),
    url(r'^mine/$', views.mine,name='mine'),
    url(r'^login/$', views.login,name='login'),
    url(r'^register/$', views.register,name='register'),
    url(r'^checkuserid/(\d+)/$', views.checkuserid,name='checkuserid'),
    url(r'^quit/$', views.quit,name='quit'),
    url(r'^changecart/(\d+)/$', views.changecart,name='changecart'),
    url(r'^saveorder/$', views.saveorder,name='saveorder'),
    url(r'^changePhone/$', views.changephone,name='changePhone'),
    url(r'^orderlist/$', views.orderlist,name='orderlist'),
    url(r'^order/(\d+)/$', views.order,name='order'),
    url(r'^order/none/$', views.ordernone,name='ordernone'),
    url(r'^favorite/$', views.favorite,name='favorite'),
    url(r'^favoritetype/$', views.favoritetype,name='favoritetype'),
    # url(r'^favoritetype/$', views.favoritetype,name='favoritetype'),
    # url(r'^favoritetype/$', views.favoritetype,name='favoritetype'),
]

project/project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('axf.urls',namespace='axf')),
]

project/axf/models.py
from django.db import models

# Create your models here.
class Wheel(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

class Nav(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

class Mustbuy(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

class Shop(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

class Mainshow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    img1 = models.CharField(max_length=10)
    childcid_1 =models.CharField(max_length=10)
    productid_1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=50)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=10,null=True)
    childcid_2 = models.CharField(max_length=10,null=True)
    productid_2 = models.CharField(max_length=10,null=True)
    longname2 = models.CharField(max_length=50,null=True)
    price2 = models.CharField(max_length=10,null=True)
    marketprice2 = models.CharField(max_length=10,null=True)

    img3 = models.CharField(max_length=10,null=True)
    childcid_3 = models.CharField(max_length=10,null=True)
    productid_3 = models.CharField(max_length=10,null=True)
    longname3 = models.CharField(max_length=50,null=True)
    price3 = models.CharField(max_length=10,null=True)
    marketprice3 = models.CharField(max_length=10,null=True)


# 分类模型
class FoodType(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    #排序方式
    typesort = models.IntegerField()
    childtypenames = models.CharField(max_length=150)


class User(models.Model):
    userAccount = models.CharField(max_length=20,unique=True)
    userPasswd = models.CharField(max_length=20)
    userName = models.CharField(max_length=20)
    userPhone = models.CharField(max_length=20)
    userAdderss = models.CharField(max_length=100)
    userImg = models.CharField(max_length=150)
    userRank = models.IntegerField()
    userToken = models.CharField(max_length=50)
    @classmethod
    def createuser(cls,account,passwd,name,phone,adderss,img,rank,token):
        u = cls(userAccount= account,userPasswd=passwd,userName=name,userPhone=phone,userAdderss=adderss,userImg=img,userRank=rank,userToken=token)
        return u
class CartManager1(models.Manager):
    def get_queryset(self):
        return super(CartManager1, self).get_queryset().filter(isDelete=False)
class CartManager2(models.Manager):
    def get_queryset(self):
        return super(CartManager2, self).get_queryset().filter(isDelete=True)
class Cart(models.Model):
    userAccount = models.CharField(max_length=20)
    productid = models.CharField(max_length=10)
    productnum = models.IntegerField()
    productprice = models.CharField(max_length=10)
    isChose = models.BooleanField(default=True)
    productimg = models.CharField(max_length=150)
    productname = models.CharField(max_length=100)
    orderid = models.CharField(max_length=20,default="0")
    isDelete = models.BooleanField(default=False)
    obj1 = CartManager1()
    obj2 = CartManager2()
    @classmethod
    def createuser(cls,userAccount,productid,productnum,productprice,isChose,productimg,productname,isDelete):
        c = cls(userAccount= userAccount,productid=productid,productnum=productnum,productprice=productprice,isChose=isChose,productimg=productimg,productname=productname,isDelete=isDelete)
        return c


class ProductGoods(models.Model):
    productid = models.CharField(max_length=10)
    productimg = models.CharField(max_length=200)
    productname = models.CharField(max_length=50)
    productlongname = models.CharField(max_length=100)
    # 是否是精选
    isxf = models.NullBooleanField(default=False)
    # 是否买一赠一
    pmdesc = models.CharField(max_length=10)
    specifics = models.CharField(max_length=20)
    price = models.FloatField(max_length=10)
    marketprice = models.FloatField(max_length=10,null=True)
    # 组id
    categoryid = models.CharField(max_length=10)
    # 子类组id
    childcid = models.CharField(max_length=10,null=True)
    childcidname = models.CharField(max_length=10,null=True)
    # 详情页id
    dealerid = models.CharField(max_length=10)
    # 库存
    storenums = models.IntegerField()
    # 销量
    productnum = models.IntegerField()
    # 定义一个变量后续用以与客户购买产品件数做比较，并赋值
    num = models.IntegerField(default=0)

class Order(models.Model):
    orderid = models.CharField(max_length=10)
    userid = models.CharField(max_length=20)
    # 订单进度
    progress = models.IntegerField()
    browsedorder = models.NullBooleanField(default=False)

    @classmethod
    def createorder(cls,orderid,userid,progress):
        o = cls(orderid=orderid,userid=userid,progress=progress)
        return o

class Favorite(models.Model):
    userAccount = models.CharField(max_length=20)
    productid = models.CharField(max_length=10)
    isDelete = models.BooleanField(default=False)
    noRepeat = models.CharField(max_length=30,default=1)
    @classmethod
    def createfavorite(cls,userAccount,productid,noRepeat,isDelete):
        f = cls(userAccount=userAccount,productid=productid,noRepeat=noRepeat,isDelete=isDelete)
        return f

project/axf/forms/login.py
from django import forms



class LoginForm(forms.Form):
    username = forms.CharField(max_length=12,min_length=6,
required=True,error_messages={'required':'用户账号不能为空','invalid':'格式错误'},
widget=forms.TextInput(attrs={'class':'c'}))
    passwd = forms.CharField(max_length=16,min_length=6,
widget=forms.PasswordInput)

project/axf/views.py
from pprint import pprint

from django.contrib.auth import logout
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
import time,random,os
from django.conf import settings
from django.urls import reverse
from axf.forms.login import LoginForm
from axf.models import Wheel, Nav, Mustbuy, Shop, Mainshow, FoodType, User, Cart, ProductGoods, Order, Favorite


def home(request):
    wheelslist = Wheel.objects.all()
    navlist = Nav.objects.all()
    mustbuylist = Mustbuy.objects.all()
    shoplist = Shop.objects.all()
    shop1 = shoplist[0]
    shop2 = shoplist[1:3]
    shop3 = shoplist[3:7]
    shop4 = shoplist[7:11]
    mainlist = Mainshow.objects.all()
    return render(request,'axf/home.html',{'title':'主页','wheelslist':wheelslist,'navlist':navlist,'mustbuylist':mustbuylist,'shop1':shop1,'shop2':shop2,'shop3':shop3,'shop4':shop4,'mainlist':mainlist})

def market(request,categoryid,cid,sortid):
    leftSliter = FoodType.objects.all()
    if cid == '0':
        productlist = ProductGoods.objects.filter(categoryid=categoryid)
    else:
        productlist = ProductGoods.objects.filter(categoryid=categoryid,childcid=cid)
    if sortid == "1":
        productlist = productlist.order_by("productnum")
    elif sortid == "2":
        productlist = productlist.order_by("price")
    elif sortid == "3":
        productlist = productlist.order_by("-price")
    group = leftSliter.get(typeid=categoryid)
    childlist = []
    arr1 = group.childtypenames.split("#")
    for i in arr1:
        arr2 = i.split(":")
        obj = {"childcidname":arr2[0],"childcid":arr2[1]}
        childlist.append(obj)
    token = request.session.get('token')
    cartlist = []
    favoritelist = []
    fidlist = []
    if token:
        user = User.objects.get(userToken=token)
        cartlist = Cart.obj1.filter(userAccount=user.userAccount)
        favoritelist = Favorite.objects.filter(userAccount=user.userAccount)
    for f in favoritelist:
        fidlist.append(f.productid)
    # print("fidlist",fidlist)
    for p in productlist:
        # print(p.productid)
        for c in cartlist:
            if c.productid == p.productid:
                p.num = c.productnum
                # print('num',p.num)
                continue
    return render(request,'axf/market.html',{'title':'闪送超市','leftSliter':leftSliter,'productlist':productlist,'childlist':childlist,'categoryid':categoryid,'cid':cid,'fidlist':fidlist})




def cart(request):
    cartlist = []
    token = request.session.get('token')
    username = ""
    userphone = ""
    useradderss = ""
    totalprice = 0
    if token != None:
        user = User.objects.get(userToken=token)
        username = user.userName
        userphone = user.userPhone
        useradderss = user.userAdderss
        cartlist = Cart.obj1.filter(userAccount=user.userAccount)
        for c in cartlist:
            unitprice = float(c.productprice)*c.productnum
            totalprice += unitprice
            # print(totalprice)
    return render(request,'axf/cart.html',{'title':'购物车','cartlist':cartlist,'username':username,'userphone':userphone,
                                           'useradderss':useradderss,'totalprice':totalprice})

def changecart(request,flag):
    # 首先判断用户是否登录
    token = request.session.get('token')
    if token==None:
        return JsonResponse({'data':-1,'status':'error'})
    productid = request.POST.get('productid')
    user = User.objects.get(userToken=token)
    product = ProductGoods.objects.get(productid=productid)
    if flag == '0':
        if product.storenums == 0:
            return JsonResponse({'data':-2,'status':'error'})
        carts = Cart.obj1.filter(userAccount=user.userAccount)
        c = None
        if carts.count() == 0:
            c = Cart.createuser(user.userAccount,productid,1,product.price,True,product.productimg,product.productlongname,False)
            c.save()
        else:
            try:
                c = carts.get(productid=productid)
                # print(c.productid)
                c.productnum += 1
                c.productprice = '%.2f'%(float(product.price)*c.productnum)
                c.save()
            except Cart.DoesNotExist as e:
                c = Cart.createuser(user.userAccount, productid, 1, product.price, True, product.productimg,product.productlongname, False)
                # print(c.productid)
                c.save()
        product.storenums -= 1
        product.save()
        return JsonResponse({'data':c.productnum,'price':c.productprice,'status':'success'})
    elif flag == '1':
        carts = Cart.obj1.filter(userAccount=user.userAccount)
        # print(len(carts))
        # print(carts.count())
        # print(productid)
        c = None
        if carts.count() == 0:
            return JsonResponse({'data':-2, 'status': 'error'})
        else:
            try:
                # print('productid',productid)
                c = carts.get(productid=productid)
                c.productnum -= 1
                # print(c.productnum)
                c.productprice = '%.2f'%(float(product.price)*c.productnum)
                if c.productnum == 0:
                    c.delete()
                else:
                    # print(c.productnum)
                    c.save()
            except Cart.DoesNotExist as e:
                return JsonResponse({'data': -2, 'status': 'error'})
        product.storenums += 1
        product.save()
        return JsonResponse({'data':c.productnum,'price':c.productprice,'status':'success'})
    elif flag == '2':
        carts = Cart.obj1.filter(userAccount=user.userAccount)
        c = carts.get(productid=productid)
        c.isChose = not c.isChose
        c.save()
        str = ""
        color = "white"
        if c.isChose:
            str='&#8730;'
            color = 'yellow'
        return JsonResponse({'data':str,'status':'success','color':color})
    elif flag == '3':
        text = request.POST.get('text')
        if text:
            carts = Cart .obj1.filter(userAccount=user.userAccount)
            for c in carts:
                c.isChose = True
                c.save()
            str = "&#8730;"
            color = "yellow"
            return JsonResponse({'data': str, 'status': 'success', 'color': color})
        else:
            carts = Cart.obj1.filter(userAccount=user.userAccount)
            for c in carts:
                c.isChose = False
                c.save()
            str = ""
            color = "white"
            return JsonResponse({'data': str, 'status': 'success', 'color': color})
    elif flag == '4':
        try:
            carts = Cart.obj1.filter(userAccount=user.userAccount)
            c = carts.get(productid=productid)
            str = ""
            color = "white"
            # print(c.productname)
            # print(c.isChose)
            if c.isChose:
                str = '&#8730;'
                color = 'yellow'
            return JsonResponse({'data':str,'status':'success','color':color,'productid':productid})
        except Cart.DoesNotExist as e:
            return JsonResponse({'data': -2, 'status': 'error'})

def mine(request):
    username = request.session.get('username','未登录')
    userimg = ""
    userrank = "等级"
    try:
        user = User.objects.get(userName=username)
        userimg = user.userImg
        userrank = user.userRank
        return render(request,'axf/mine.html',{'title':'我的','username':username,'userimg':userimg,'userrank':userrank})
    except Exception as e:
        return render(request,'axf/mine.html',{'title':'我的','username':username,'userimg':userimg,'userrank':userrank})


def login(request):
    if request.method == 'POST':
        f = LoginForm(request.POST)
        if f.is_valid():
            nameid = f.cleaned_data['username']
            pswd = f.cleaned_data['passwd']
            try:
                user = User.objects.get(userAccount=nameid)
                if user.userPasswd != pswd:
                    return redirect('/login/')

            except User.DoesNotExist as e:
                return redirect('/login/')
            token = random.randrange(1, 100000)
            user.userToken = str(token)
            user.save()
            request.session['username'] = user.userName
            request.session['token'] = user.userToken
            return redirect('/mine/')
        else:
            return render(request, 'axf/login.html', {'title': '登录','form': f,'error':f.errors})
    else:
        f = LoginForm()
        return render(request,'axf/login.html',{'title':'登录','form':f})


def register(request):
    if request.method == 'POST':
        userAccount = request.POST.get('userAccount')
        userPasswd = request.POST.get('userPasswd')
        userName = request.POST.get('userName')
        userPhone = request.POST.get('userPhone')
        userAdderss = request.POST.get('userAddress')
        userRank = 0
        token = random.randrange(1,100000)
        userToken = str(token)
        f = request.FILES['userImg']
        userImg = os.path.join(settings.MEDIA_ROOT,userAccount+'.png')
        with open(userImg,'wb') as fp:
            for data in f.chunks():
                fp.write(data)
        user = User.createuser(userAccount,userPasswd,userName,userPhone,userAdderss,userRank,userToken,userImg)
        user.save()
        request.session['username'] = userName
        request.session['token'] = userToken
        return redirect('/mine/')
    else:
        return render(request,'axf/register.html',{'title':'注册'})


def checkuserid(request,flag):
    userid = request.POST.get('userid')
    if flag == "0":
        try:
            user = User.objects.get(userAccount=userid)
            return JsonResponse({'data':'该用户已经被注册','status':'error'})
        except User.DoesNotExist as e:
            return JsonResponse({'data':'ok','status':'success'})
    elif flag == "1":
        try:
            user = User.objects.get(userAccount=userid)

project/templates/axf/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/swiper.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}"/>

    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/swiper.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/base.js' %}"></script>

    {% block linkscript %}
    {% endblock linkscript %}


</head>
<body>
<header id="header">
    <div id="bg1" class="bg"><div></div></div>
    <div id="bg2" class="bg"><div></div></div>
</header>
<div id="box">
    {% block base %}
    {% endblock base %}
</div>
<footer id="footer">
    <a id="footerhome" class="footer_a" href="{% url 'axf:home' %}">
        <dl>
            <dt><span id="footer_span1" class="footer_span" style="background-image: url('/static/main/img/home.png');"></span></dt>
            <dd class="footer_spandd">主页</dd>
        </dl>
        <div id="dhome" class="markdiamond"></div>
    </a>
{#    <a id="footermarket" class="footer_a" href="/market/103532/0/0/">#}
    <a id="footermarket" class="footer_a" href="{% url 'axf:market' 103532 0 0 %}">
        <dl>
            <dt><span id="footer_span2" class="footer_span" style="background-image: url('/static/main/img/market.png');"></span></dt>
            <dd class="footer_spandd">闪送超市</dd>
        </dl>
        <div id="dmarket" class="markdiamond"></div>
    </a>
    <a id="footercart" class="footer_a" href="{% url 'axf:cart' %}">
        <dl>
            <dt><span id="footer_span3" class="footer_span" style="background-image: url('/static/main/img/cart.png');"></span></dt>
            <dd class="footer_spandd">购物车</dd>
        </dl>
        <div id="dcart" class="markdiamond"></div>
    </a>
    <a id="footermine" class="footer_a" href="{% url 'axf:mine' %}">
        <dl>
            <dt><span id="footer_span4" class="footer_span" style="background-image: url('/static/main/img/mine.png');"></span></dt>
            <dd class="footer_spandd">我的</dd>
        </dl>
        <div id="dmine" class="markdiamond"></div>
    </a>
</footer>
</body>
</html>

project/templates/axf/cart.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'cart/css/cart.css' %}"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'cart/js/cart.js' %}"></script>
{% endblock linkscript %}

{% block base %}
<div id="cart">
<h3><b>购物车</b></h3>
<section class="full">
    <section>
        <ul>
            <li>
                <div class="clear">
                    <p class="infoJustify">收件人<b></b></p><p>:<span>{{ username }}</span></p>
                </div>
            </li>
            <li>
                <div class="clear">
                    <p class="infoJustify">电话<b></b></p><p>:<span>{{ userphone }}</span><a class="change" href="{% url 'axf:changePhone' %}">修改></a></p>
                </div>
            </li>
            <li>
                <div class="clear">
                    <p class="infoJustify">收货地址<b></b></p><p>:<span>{{ useradderss }}</span></p>
                </div>
            </li>
        </ul>
        <section class="bill">
            <p>闪送超市</p>
            <p>￥0起送，22:00前满￥30免运费</p>
            <a>凑单专区</a>
        </section>
        <section id="delivery1" class="delivery">
            <span>收货时间</span><span>一小时送达</span>
            <a>可预订></a>
        </section>
        <section id="delivery2" class="delivery">
            <span>收货备注</span>
            <input type="text" placeholder="可输入一百字以内特殊要求内容" />
        </section>
        <menu>
            <ul>
                {% for item in cartlist %}
                <li id="{{ item.productid }}li" class="menulist">
                    <div class="confirm">
                    <span class="ischose" goodsid="{{ item.productid }}">
                        <span id="{{ item.productid }}a" class="productchose">

                        {% ifequal True item.isChose %}
                            &#8730;
                        {% endifequal %}
                         </span>
{#                        {% ifnotequal True item.isChose %}#}
{#                                <span id="{{ item.productid }}a" style="color:white;background-color: white">#}
{#                            &#8730;#}
{#                                </span>#}
{#                            {% endifnotequal %}#}
                    </span>
                    </div>
                    <a href="#">
                        <img src="{{ item.productimg }}" />
                        <p>{{ item.productname }}</p>
                        <span id="{{ item.productid }}price" class="productprice">{{ item.productprice }}</span>
                    </a>
                    <section>
                        <button class="subShopping" ga="{{ item.productid }}"><div class="symbol1">-</div></button>
                        <span id="{{ item.productid }}">{{ item.productnum }}</span>
                        <button class="addShopping" ga="{{ item.productid }}"><div class="symbol2">+</div></button>
                    </section>
                </li>
                {% endfor %}
                <li class="payTheBill">
                    <div class="confirm">
                        <span id ="outertotalChose">
                            <span id="innertotalChose">
{#                            {% for trueFlag %}#}
                            &#8730;
{#                            {% endfor %}#}
                            </span>
                        </span>
                    </div>
                <p>
                    <span>&nbsp;全选&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <span>共计:</span>
                    <span id="totalprice">{{ totalprice }}</span></p>
                <a id="ok">选好了</a>
                </li>
            </ul>
        </menu>
    </section>
</section>
</div>
{% endblock base %}

project/templates/axf/changePhone.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/changePhone.css' %}"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/changePhone.js' %}"></script>
{% endblock linkscript %}
{% block base %}
<div id="changePhone">
<div id="header">
    <a href="{% url 'axf:mine' %}"><p>返回</p></a>
</div>
    <br>
<form class="form-horizontal" action="{% url 'axf:changePhone' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group">
        <span class="input-group-addon">账号</span>
        <input id="account" type="text" class="form-control" placeholder="账号长度为6~12个字符" aria-describedby="basic-addon1" name="userAccount">
    </div>
    <span id="accounterr" class="error">账号或格式错误</span>
    <span id="checkerr" class="error">账号不存在，请重新输入</span>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">电话</span>
        <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userPhone">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">修改</span>
        <input type="submit" class="form-control" aria-describedby="basic-addon1" value="确认提交">
    </div>
</form>
</div>
{% endblock base %}

project/templates/axf/mine.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/mine.css' %}"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/mine.js' %}"></script>
{% endblock linkscript %}

{% block base %}
    <div id="mine">
        <section id="fixed">
            {% if userimg %}
            <span style="background-image: url('{{ userimg }}')"></span>
            {% else %}
            <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            <p><a href="{% url 'axf:login' %}">{{ username }}</a></p>
            <p><span class="glyphicon glyphicon-fire" id="glyphicon-fire"></span><span id="rank">{{ userrank }}</span></p>
            <a id="regis" href="{% url 'axf:register' %}">注册</a>
            <p><a href="/favoritetype/"><span class="glyphicon glyphicon-heart" id="glyphicon-heart"></span>商品收藏</a></p>
        </section>
        <section id="notfixed">
            <p><span>我的订单</span><a href="{% url 'axf:orderlist' %}">查看我的订单</a></p>
            <nav id="nav">
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-usd"></span>
                                </dt>
                                <dd>代付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-envelope"></span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-retweet"></span>
                                </dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-bullhorn"></span>
                                </dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-credit-card"></span>
                                </dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-import"></span>
                                </dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-phone-alt"></span>
                                </dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-asterisk"></span>
                                </dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            <p><a href="{% url 'axf:quit' %}">退出当前账号</a></p>
        </section>
    </div>
{% endblock base %}

project/templates/axf/order.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/order.css' %}"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/order.js' %}"></script>
{% endblock linkscript %}

{% block base %}
<div id="order">
<div></div>
<ul>
    {% for item in cartlist %}
    <li id="{{ item.productid }}li" class="menulist">
        <img src="{{ item.productimg }}"/>
        <p id="firstp">{{ item.productname }}</p>
        <p class="productprice">价格:{{ item.productprice }}</p>
        <p class="productnum">数量:{{ item.productnum }}</p>
    </li>
    {% endfor %}

</ul>
<section>
    <a id="otherOrders" href="{% url 'axf:orderlist' %}">看其它订单</a>
    <a id="nextorder" href="/order/{{ nextorderid }}/">下一个订单</a>
</section>
</div>
{% endblock base %}

project/templates/axf/ordernone.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/ordernone.css' %}"/>
{% endblock linkscript %}
{% block base %}
<div id="ordernone">
<p>没有订单了！</p>
<a href="{% url 'axf:orderlist' %}"><p>点我</p></a>
</div>
{% endblock base %}